<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SettingRankSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('group_rank_settings')->insert([
            [
                'id' => 1,
                'group_id' => 1,
                'rank_name' => 'member',
                'rank_position' => 1,
                'lot_rebate_currency' => 'USD',
                'lot_rebate_amount' => 0,
                'min_direct_referral' => null,
                'min_direct_referral_rank_id' => null,
                'group_sales_currency' => null,
                'max_capped_per_line' => 0,
                'min_group_sales' => 0,
                'edited_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'group_id' => 1,
                'rank_name' => 'salesman',
                'rank_position' => 2,
                'lot_rebate_currency' => 'USD',
                'lot_rebate_amount' => 3,
                'min_direct_referral' => 2,
                'min_direct_referral_rank_id' => 1,
                'group_sales_currency' => 'CNY',
                'max_capped_per_line' => 74000,
                'min_group_sales' => 148000,
                'edited_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'group_id' => 1,
                'rank_name' => 'county_agent',
                'rank_position' => 3,
                'lot_rebate_currency' => 'USD',
                'lot_rebate_amount' => 6,
                'min_direct_referral' => 2,
                'min_direct_referral_rank_id' => 2,
                'group_sales_currency' => 'CNY',
                'max_capped_per_line' => 148000,
                'min_group_sales' => 296000,
                'edited_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'group_id' => 1,
                'rank_name' => 'municipal_agent',
                'rank_position' => 4,
                'lot_rebate_currency' => 'USD',
                'lot_rebate_amount' => 9,
                'min_direct_referral' => 2,
                'min_direct_referral_rank_id' => 3,
                'group_sales_currency' => 'CNY',
                'max_capped_per_line' => 296000,
                'min_group_sales' => 592000,
                'edited_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'group_id' => 1,
                'rank_name' => 'provincial_agent',
                'rank_position' => 5,
                'lot_rebate_currency' => 'USD',
                'lot_rebate_amount' => 12,
                'min_direct_referral' => 3,
                'min_direct_referral_rank_id' => 4,
                'group_sales_currency' => 'CNY',
                'max_capped_per_line' => 592000,
                'min_group_sales' => 1776000,
                'edited_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'group_id' => 1,
                'rank_name' => 'general_agent',
                'rank_position' => 6,
                'lot_rebate_currency' => 'USD',
                'lot_rebate_amount' => 15,
                'min_direct_referral' => 3,
                'min_direct_referral_rank_id' => 5,
                'group_sales_currency' => 'CNY',
                'max_capped_per_line' => 1776000,
                'min_group_sales' => 5328000,
                'edited_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
        ]);
    }
}
